// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pswmgr.proto

#ifndef PROTOBUF_pswmgr_2eproto__INCLUDED
#define PROTOBUF_pswmgr_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace pswmgr {
class AuthReply;
class AuthReplyDefaultTypeInternal;
extern AuthReplyDefaultTypeInternal _AuthReply_default_instance_;
class AuthenticationRequest;
class AuthenticationRequestDefaultTypeInternal;
extern AuthenticationRequestDefaultTypeInternal _AuthenticationRequest_default_instance_;
class PasswordEntry;
class PasswordEntryDefaultTypeInternal;
extern PasswordEntryDefaultTypeInternal _PasswordEntry_default_instance_;
class PasswordList;
class PasswordListDefaultTypeInternal;
extern PasswordListDefaultTypeInternal _PasswordList_default_instance_;
class SimpleReply;
class SimpleReplyDefaultTypeInternal;
extern SimpleReplyDefaultTypeInternal _SimpleReply_default_instance_;
class SimpleRequest;
class SimpleRequestDefaultTypeInternal;
extern SimpleRequestDefaultTypeInternal _SimpleRequest_default_instance_;
class UserCreationReply;
class UserCreationReplyDefaultTypeInternal;
extern UserCreationReplyDefaultTypeInternal _UserCreationReply_default_instance_;
class UserCreationRequest;
class UserCreationRequestDefaultTypeInternal;
extern UserCreationRequestDefaultTypeInternal _UserCreationRequest_default_instance_;
class UserPasswordUpdateRequest;
class UserPasswordUpdateRequestDefaultTypeInternal;
extern UserPasswordUpdateRequestDefaultTypeInternal _UserPasswordUpdateRequest_default_instance_;
}  // namespace pswmgr

namespace pswmgr {

namespace protobuf_pswmgr_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_pswmgr_2eproto

// ===================================================================

class AuthenticationRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.AuthenticationRequest) */ {
 public:
  AuthenticationRequest();
  virtual ~AuthenticationRequest();

  AuthenticationRequest(const AuthenticationRequest& from);

  inline AuthenticationRequest& operator=(const AuthenticationRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationRequest& default_instance();

  static inline const AuthenticationRequest* internal_default_instance() {
    return reinterpret_cast<const AuthenticationRequest*>(
               &_AuthenticationRequest_default_instance_);
  }

  void Swap(AuthenticationRequest* other);

  // implements Message ----------------------------------------------

  inline AuthenticationRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationRequest& from);
  void MergeFrom(const AuthenticationRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // int32 tfa_token = 3;
  void clear_tfa_token();
  static const int kTfaTokenFieldNumber = 3;
  ::google::protobuf::int32 tfa_token() const;
  void set_tfa_token(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pswmgr.AuthenticationRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::int32 tfa_token_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserPasswordUpdateRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.UserPasswordUpdateRequest) */ {
 public:
  UserPasswordUpdateRequest();
  virtual ~UserPasswordUpdateRequest();

  UserPasswordUpdateRequest(const UserPasswordUpdateRequest& from);

  inline UserPasswordUpdateRequest& operator=(const UserPasswordUpdateRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserPasswordUpdateRequest& default_instance();

  static inline const UserPasswordUpdateRequest* internal_default_instance() {
    return reinterpret_cast<const UserPasswordUpdateRequest*>(
               &_UserPasswordUpdateRequest_default_instance_);
  }

  void Swap(UserPasswordUpdateRequest* other);

  // implements Message ----------------------------------------------

  inline UserPasswordUpdateRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UserPasswordUpdateRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserPasswordUpdateRequest& from);
  void MergeFrom(const UserPasswordUpdateRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserPasswordUpdateRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // @@protoc_insertion_point(class_scope:pswmgr.UserPasswordUpdateRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserCreationRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.UserCreationRequest) */ {
 public:
  UserCreationRequest();
  virtual ~UserCreationRequest();

  UserCreationRequest(const UserCreationRequest& from);

  inline UserCreationRequest& operator=(const UserCreationRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserCreationRequest& default_instance();

  static inline const UserCreationRequest* internal_default_instance() {
    return reinterpret_cast<const UserCreationRequest*>(
               &_UserCreationRequest_default_instance_);
  }

  void Swap(UserCreationRequest* other);

  // implements Message ----------------------------------------------

  inline UserCreationRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  UserCreationRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserCreationRequest& from);
  void MergeFrom(const UserCreationRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserCreationRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string username = 1;
  void clear_username();
  static const int kUsernameFieldNumber = 1;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 2;
  void clear_password();
  static const int kPasswordFieldNumber = 2;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // bool admin = 3;
  void clear_admin();
  static const int kAdminFieldNumber = 3;
  bool admin() const;
  void set_admin(bool value);

  // bool add_2fa = 4;
  void clear_add_2fa();
  static const int kAdd2FaFieldNumber = 4;
  bool add_2fa() const;
  void set_add_2fa(bool value);

  // @@protoc_insertion_point(class_scope:pswmgr.UserCreationRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  bool admin_;
  bool add_2fa_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserCreationReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.UserCreationReply) */ {
 public:
  UserCreationReply();
  virtual ~UserCreationReply();

  UserCreationReply(const UserCreationReply& from);

  inline UserCreationReply& operator=(const UserCreationReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserCreationReply& default_instance();

  static inline const UserCreationReply* internal_default_instance() {
    return reinterpret_cast<const UserCreationReply*>(
               &_UserCreationReply_default_instance_);
  }

  void Swap(UserCreationReply* other);

  // implements Message ----------------------------------------------

  inline UserCreationReply* New() const PROTOBUF_FINAL { return New(NULL); }

  UserCreationReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UserCreationReply& from);
  void MergeFrom(const UserCreationReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserCreationReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 scratch_codes = 4;
  int scratch_codes_size() const;
  void clear_scratch_codes();
  static const int kScratchCodesFieldNumber = 4;
  ::google::protobuf::int32 scratch_codes(int index) const;
  void set_scratch_codes(int index, ::google::protobuf::int32 value);
  void add_scratch_codes(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      scratch_codes() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_scratch_codes();

  // string secret = 2;
  void clear_secret();
  static const int kSecretFieldNumber = 2;
  const ::std::string& secret() const;
  void set_secret(const ::std::string& value);
  #if LANG_CXX11
  void set_secret(::std::string&& value);
  #endif
  void set_secret(const char* value);
  void set_secret(const char* value, size_t size);
  ::std::string* mutable_secret();
  ::std::string* release_secret();
  void set_allocated_secret(::std::string* secret);

  // bytes qrcode = 3;
  void clear_qrcode();
  static const int kQrcodeFieldNumber = 3;
  const ::std::string& qrcode() const;
  void set_qrcode(const ::std::string& value);
  #if LANG_CXX11
  void set_qrcode(::std::string&& value);
  #endif
  void set_qrcode(const char* value);
  void set_qrcode(const void* value, size_t size);
  ::std::string* mutable_qrcode();
  ::std::string* release_qrcode();
  void set_allocated_qrcode(::std::string* qrcode);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:pswmgr.UserCreationReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > scratch_codes_;
  mutable int _scratch_codes_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr secret_;
  ::google::protobuf::internal::ArenaStringPtr qrcode_;
  bool success_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimpleRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.SimpleRequest) */ {
 public:
  SimpleRequest();
  virtual ~SimpleRequest();

  SimpleRequest(const SimpleRequest& from);

  inline SimpleRequest& operator=(const SimpleRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleRequest& default_instance();

  static inline const SimpleRequest* internal_default_instance() {
    return reinterpret_cast<const SimpleRequest*>(
               &_SimpleRequest_default_instance_);
  }

  void Swap(SimpleRequest* other);

  // implements Message ----------------------------------------------

  inline SimpleRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  SimpleRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SimpleRequest& from);
  void MergeFrom(const SimpleRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SimpleRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool empty = 1;
  void clear_empty();
  static const int kEmptyFieldNumber = 1;
  bool empty() const;
  void set_empty(bool value);

  // @@protoc_insertion_point(class_scope:pswmgr.SimpleRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool empty_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimpleReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.SimpleReply) */ {
 public:
  SimpleReply();
  virtual ~SimpleReply();

  SimpleReply(const SimpleReply& from);

  inline SimpleReply& operator=(const SimpleReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleReply& default_instance();

  static inline const SimpleReply* internal_default_instance() {
    return reinterpret_cast<const SimpleReply*>(
               &_SimpleReply_default_instance_);
  }

  void Swap(SimpleReply* other);

  // implements Message ----------------------------------------------

  inline SimpleReply* New() const PROTOBUF_FINAL { return New(NULL); }

  SimpleReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SimpleReply& from);
  void MergeFrom(const SimpleReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SimpleReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:pswmgr.SimpleReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool success_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AuthReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.AuthReply) */ {
 public:
  AuthReply();
  virtual ~AuthReply();

  AuthReply(const AuthReply& from);

  inline AuthReply& operator=(const AuthReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthReply& default_instance();

  static inline const AuthReply* internal_default_instance() {
    return reinterpret_cast<const AuthReply*>(
               &_AuthReply_default_instance_);
  }

  void Swap(AuthReply* other);

  // implements Message ----------------------------------------------

  inline AuthReply* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthReply& from);
  void MergeFrom(const AuthReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string token = 2;
  void clear_token();
  static const int kTokenFieldNumber = 2;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  #if LANG_CXX11
  void set_token(::std::string&& value);
  #endif
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // bool token_needed_for_2fa = 3;
  void clear_token_needed_for_2fa();
  static const int kTokenNeededFor2FaFieldNumber = 3;
  bool token_needed_for_2fa() const;
  void set_token_needed_for_2fa(bool value);

  // @@protoc_insertion_point(class_scope:pswmgr.AuthReply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  bool success_;
  bool token_needed_for_2fa_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PasswordEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.PasswordEntry) */ {
 public:
  PasswordEntry();
  virtual ~PasswordEntry();

  PasswordEntry(const PasswordEntry& from);

  inline PasswordEntry& operator=(const PasswordEntry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PasswordEntry& default_instance();

  static inline const PasswordEntry* internal_default_instance() {
    return reinterpret_cast<const PasswordEntry*>(
               &_PasswordEntry_default_instance_);
  }

  void Swap(PasswordEntry* other);

  // implements Message ----------------------------------------------

  inline PasswordEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  PasswordEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PasswordEntry& from);
  void MergeFrom(const PasswordEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PasswordEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string account_name = 1;
  void clear_account_name();
  static const int kAccountNameFieldNumber = 1;
  const ::std::string& account_name() const;
  void set_account_name(const ::std::string& value);
  #if LANG_CXX11
  void set_account_name(::std::string&& value);
  #endif
  void set_account_name(const char* value);
  void set_account_name(const char* value, size_t size);
  ::std::string* mutable_account_name();
  ::std::string* release_account_name();
  void set_allocated_account_name(::std::string* account_name);

  // string username = 2;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  #if LANG_CXX11
  void set_username(::std::string&& value);
  #endif
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // string password = 3;
  void clear_password();
  static const int kPasswordFieldNumber = 3;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // string extra = 4;
  void clear_extra();
  static const int kExtraFieldNumber = 4;
  const ::std::string& extra() const;
  void set_extra(const ::std::string& value);
  #if LANG_CXX11
  void set_extra(::std::string&& value);
  #endif
  void set_extra(const char* value);
  void set_extra(const char* value, size_t size);
  ::std::string* mutable_extra();
  ::std::string* release_extra();
  void set_allocated_extra(::std::string* extra);

  // @@protoc_insertion_point(class_scope:pswmgr.PasswordEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr account_name_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::internal::ArenaStringPtr extra_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PasswordList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pswmgr.PasswordList) */ {
 public:
  PasswordList();
  virtual ~PasswordList();

  PasswordList(const PasswordList& from);

  inline PasswordList& operator=(const PasswordList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PasswordList& default_instance();

  static inline const PasswordList* internal_default_instance() {
    return reinterpret_cast<const PasswordList*>(
               &_PasswordList_default_instance_);
  }

  void Swap(PasswordList* other);

  // implements Message ----------------------------------------------

  inline PasswordList* New() const PROTOBUF_FINAL { return New(NULL); }

  PasswordList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PasswordList& from);
  void MergeFrom(const PasswordList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PasswordList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pswmgr.PasswordEntry passwords = 1;
  int passwords_size() const;
  void clear_passwords();
  static const int kPasswordsFieldNumber = 1;
  const ::pswmgr::PasswordEntry& passwords(int index) const;
  ::pswmgr::PasswordEntry* mutable_passwords(int index);
  ::pswmgr::PasswordEntry* add_passwords();
  ::google::protobuf::RepeatedPtrField< ::pswmgr::PasswordEntry >*
      mutable_passwords();
  const ::google::protobuf::RepeatedPtrField< ::pswmgr::PasswordEntry >&
      passwords() const;

  // @@protoc_insertion_point(class_scope:pswmgr.PasswordList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::pswmgr::PasswordEntry > passwords_;
  mutable int _cached_size_;
  friend struct  protobuf_pswmgr_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AuthenticationRequest

// string username = 1;
inline void AuthenticationRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthenticationRequest::username() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthenticationRequest.username)
  return username_.GetNoArena();
}
inline void AuthenticationRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.AuthenticationRequest.username)
}
#if LANG_CXX11
inline void AuthenticationRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.AuthenticationRequest.username)
}
#endif
inline void AuthenticationRequest::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.AuthenticationRequest.username)
}
inline void AuthenticationRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.AuthenticationRequest.username)
}
inline ::std::string* AuthenticationRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.AuthenticationRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthenticationRequest::release_username() {
  // @@protoc_insertion_point(field_release:pswmgr.AuthenticationRequest.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthenticationRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.AuthenticationRequest.username)
}

// string password = 2;
inline void AuthenticationRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthenticationRequest::password() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthenticationRequest.password)
  return password_.GetNoArena();
}
inline void AuthenticationRequest::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.AuthenticationRequest.password)
}
#if LANG_CXX11
inline void AuthenticationRequest::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.AuthenticationRequest.password)
}
#endif
inline void AuthenticationRequest::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.AuthenticationRequest.password)
}
inline void AuthenticationRequest::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.AuthenticationRequest.password)
}
inline ::std::string* AuthenticationRequest::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.AuthenticationRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthenticationRequest::release_password() {
  // @@protoc_insertion_point(field_release:pswmgr.AuthenticationRequest.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthenticationRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.AuthenticationRequest.password)
}

// int32 tfa_token = 3;
inline void AuthenticationRequest::clear_tfa_token() {
  tfa_token_ = 0;
}
inline ::google::protobuf::int32 AuthenticationRequest::tfa_token() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthenticationRequest.tfa_token)
  return tfa_token_;
}
inline void AuthenticationRequest::set_tfa_token(::google::protobuf::int32 value) {
  
  tfa_token_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.AuthenticationRequest.tfa_token)
}

// -------------------------------------------------------------------

// UserPasswordUpdateRequest

// string username = 1;
inline void UserPasswordUpdateRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserPasswordUpdateRequest::username() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserPasswordUpdateRequest.username)
  return username_.GetNoArena();
}
inline void UserPasswordUpdateRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserPasswordUpdateRequest.username)
}
#if LANG_CXX11
inline void UserPasswordUpdateRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserPasswordUpdateRequest.username)
}
#endif
inline void UserPasswordUpdateRequest::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserPasswordUpdateRequest.username)
}
inline void UserPasswordUpdateRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserPasswordUpdateRequest.username)
}
inline ::std::string* UserPasswordUpdateRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserPasswordUpdateRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserPasswordUpdateRequest::release_username() {
  // @@protoc_insertion_point(field_release:pswmgr.UserPasswordUpdateRequest.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserPasswordUpdateRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserPasswordUpdateRequest.username)
}

// string password = 2;
inline void UserPasswordUpdateRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserPasswordUpdateRequest::password() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserPasswordUpdateRequest.password)
  return password_.GetNoArena();
}
inline void UserPasswordUpdateRequest::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserPasswordUpdateRequest.password)
}
#if LANG_CXX11
inline void UserPasswordUpdateRequest::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserPasswordUpdateRequest.password)
}
#endif
inline void UserPasswordUpdateRequest::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserPasswordUpdateRequest.password)
}
inline void UserPasswordUpdateRequest::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserPasswordUpdateRequest.password)
}
inline ::std::string* UserPasswordUpdateRequest::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserPasswordUpdateRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserPasswordUpdateRequest::release_password() {
  // @@protoc_insertion_point(field_release:pswmgr.UserPasswordUpdateRequest.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserPasswordUpdateRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserPasswordUpdateRequest.password)
}

// -------------------------------------------------------------------

// UserCreationRequest

// string username = 1;
inline void UserCreationRequest::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserCreationRequest::username() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationRequest.username)
  return username_.GetNoArena();
}
inline void UserCreationRequest::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationRequest.username)
}
#if LANG_CXX11
inline void UserCreationRequest::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserCreationRequest.username)
}
#endif
inline void UserCreationRequest::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserCreationRequest.username)
}
inline void UserCreationRequest::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserCreationRequest.username)
}
inline ::std::string* UserCreationRequest::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserCreationRequest.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserCreationRequest::release_username() {
  // @@protoc_insertion_point(field_release:pswmgr.UserCreationRequest.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserCreationRequest::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserCreationRequest.username)
}

// string password = 2;
inline void UserCreationRequest::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserCreationRequest::password() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationRequest.password)
  return password_.GetNoArena();
}
inline void UserCreationRequest::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationRequest.password)
}
#if LANG_CXX11
inline void UserCreationRequest::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserCreationRequest.password)
}
#endif
inline void UserCreationRequest::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserCreationRequest.password)
}
inline void UserCreationRequest::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserCreationRequest.password)
}
inline ::std::string* UserCreationRequest::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserCreationRequest.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserCreationRequest::release_password() {
  // @@protoc_insertion_point(field_release:pswmgr.UserCreationRequest.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserCreationRequest::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserCreationRequest.password)
}

// bool admin = 3;
inline void UserCreationRequest::clear_admin() {
  admin_ = false;
}
inline bool UserCreationRequest::admin() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationRequest.admin)
  return admin_;
}
inline void UserCreationRequest::set_admin(bool value) {
  
  admin_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationRequest.admin)
}

// bool add_2fa = 4;
inline void UserCreationRequest::clear_add_2fa() {
  add_2fa_ = false;
}
inline bool UserCreationRequest::add_2fa() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationRequest.add_2fa)
  return add_2fa_;
}
inline void UserCreationRequest::set_add_2fa(bool value) {
  
  add_2fa_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationRequest.add_2fa)
}

// -------------------------------------------------------------------

// UserCreationReply

// bool success = 1;
inline void UserCreationReply::clear_success() {
  success_ = false;
}
inline bool UserCreationReply::success() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationReply.success)
  return success_;
}
inline void UserCreationReply::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationReply.success)
}

// string secret = 2;
inline void UserCreationReply::clear_secret() {
  secret_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserCreationReply::secret() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationReply.secret)
  return secret_.GetNoArena();
}
inline void UserCreationReply::set_secret(const ::std::string& value) {
  
  secret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationReply.secret)
}
#if LANG_CXX11
inline void UserCreationReply::set_secret(::std::string&& value) {
  
  secret_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserCreationReply.secret)
}
#endif
inline void UserCreationReply::set_secret(const char* value) {
  
  secret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserCreationReply.secret)
}
inline void UserCreationReply::set_secret(const char* value, size_t size) {
  
  secret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserCreationReply.secret)
}
inline ::std::string* UserCreationReply::mutable_secret() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserCreationReply.secret)
  return secret_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserCreationReply::release_secret() {
  // @@protoc_insertion_point(field_release:pswmgr.UserCreationReply.secret)
  
  return secret_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserCreationReply::set_allocated_secret(::std::string* secret) {
  if (secret != NULL) {
    
  } else {
    
  }
  secret_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), secret);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserCreationReply.secret)
}

// bytes qrcode = 3;
inline void UserCreationReply::clear_qrcode() {
  qrcode_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserCreationReply::qrcode() const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationReply.qrcode)
  return qrcode_.GetNoArena();
}
inline void UserCreationReply::set_qrcode(const ::std::string& value) {
  
  qrcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationReply.qrcode)
}
#if LANG_CXX11
inline void UserCreationReply::set_qrcode(::std::string&& value) {
  
  qrcode_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.UserCreationReply.qrcode)
}
#endif
inline void UserCreationReply::set_qrcode(const char* value) {
  
  qrcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.UserCreationReply.qrcode)
}
inline void UserCreationReply::set_qrcode(const void* value, size_t size) {
  
  qrcode_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.UserCreationReply.qrcode)
}
inline ::std::string* UserCreationReply::mutable_qrcode() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.UserCreationReply.qrcode)
  return qrcode_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserCreationReply::release_qrcode() {
  // @@protoc_insertion_point(field_release:pswmgr.UserCreationReply.qrcode)
  
  return qrcode_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserCreationReply::set_allocated_qrcode(::std::string* qrcode) {
  if (qrcode != NULL) {
    
  } else {
    
  }
  qrcode_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), qrcode);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.UserCreationReply.qrcode)
}

// repeated int32 scratch_codes = 4;
inline int UserCreationReply::scratch_codes_size() const {
  return scratch_codes_.size();
}
inline void UserCreationReply::clear_scratch_codes() {
  scratch_codes_.Clear();
}
inline ::google::protobuf::int32 UserCreationReply::scratch_codes(int index) const {
  // @@protoc_insertion_point(field_get:pswmgr.UserCreationReply.scratch_codes)
  return scratch_codes_.Get(index);
}
inline void UserCreationReply::set_scratch_codes(int index, ::google::protobuf::int32 value) {
  scratch_codes_.Set(index, value);
  // @@protoc_insertion_point(field_set:pswmgr.UserCreationReply.scratch_codes)
}
inline void UserCreationReply::add_scratch_codes(::google::protobuf::int32 value) {
  scratch_codes_.Add(value);
  // @@protoc_insertion_point(field_add:pswmgr.UserCreationReply.scratch_codes)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
UserCreationReply::scratch_codes() const {
  // @@protoc_insertion_point(field_list:pswmgr.UserCreationReply.scratch_codes)
  return scratch_codes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
UserCreationReply::mutable_scratch_codes() {
  // @@protoc_insertion_point(field_mutable_list:pswmgr.UserCreationReply.scratch_codes)
  return &scratch_codes_;
}

// -------------------------------------------------------------------

// SimpleRequest

// bool empty = 1;
inline void SimpleRequest::clear_empty() {
  empty_ = false;
}
inline bool SimpleRequest::empty() const {
  // @@protoc_insertion_point(field_get:pswmgr.SimpleRequest.empty)
  return empty_;
}
inline void SimpleRequest::set_empty(bool value) {
  
  empty_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.SimpleRequest.empty)
}

// -------------------------------------------------------------------

// SimpleReply

// bool success = 1;
inline void SimpleReply::clear_success() {
  success_ = false;
}
inline bool SimpleReply::success() const {
  // @@protoc_insertion_point(field_get:pswmgr.SimpleReply.success)
  return success_;
}
inline void SimpleReply::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.SimpleReply.success)
}

// -------------------------------------------------------------------

// AuthReply

// bool success = 1;
inline void AuthReply::clear_success() {
  success_ = false;
}
inline bool AuthReply::success() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthReply.success)
  return success_;
}
inline void AuthReply::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.AuthReply.success)
}

// string token = 2;
inline void AuthReply::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AuthReply::token() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthReply.token)
  return token_.GetNoArena();
}
inline void AuthReply::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.AuthReply.token)
}
#if LANG_CXX11
inline void AuthReply::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.AuthReply.token)
}
#endif
inline void AuthReply::set_token(const char* value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.AuthReply.token)
}
inline void AuthReply::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.AuthReply.token)
}
inline ::std::string* AuthReply::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.AuthReply.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AuthReply::release_token() {
  // @@protoc_insertion_point(field_release:pswmgr.AuthReply.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AuthReply::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.AuthReply.token)
}

// bool token_needed_for_2fa = 3;
inline void AuthReply::clear_token_needed_for_2fa() {
  token_needed_for_2fa_ = false;
}
inline bool AuthReply::token_needed_for_2fa() const {
  // @@protoc_insertion_point(field_get:pswmgr.AuthReply.token_needed_for_2fa)
  return token_needed_for_2fa_;
}
inline void AuthReply::set_token_needed_for_2fa(bool value) {
  
  token_needed_for_2fa_ = value;
  // @@protoc_insertion_point(field_set:pswmgr.AuthReply.token_needed_for_2fa)
}

// -------------------------------------------------------------------

// PasswordEntry

// string account_name = 1;
inline void PasswordEntry::clear_account_name() {
  account_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PasswordEntry::account_name() const {
  // @@protoc_insertion_point(field_get:pswmgr.PasswordEntry.account_name)
  return account_name_.GetNoArena();
}
inline void PasswordEntry::set_account_name(const ::std::string& value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.PasswordEntry.account_name)
}
#if LANG_CXX11
inline void PasswordEntry::set_account_name(::std::string&& value) {
  
  account_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.PasswordEntry.account_name)
}
#endif
inline void PasswordEntry::set_account_name(const char* value) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.PasswordEntry.account_name)
}
inline void PasswordEntry::set_account_name(const char* value, size_t size) {
  
  account_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.PasswordEntry.account_name)
}
inline ::std::string* PasswordEntry::mutable_account_name() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.PasswordEntry.account_name)
  return account_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PasswordEntry::release_account_name() {
  // @@protoc_insertion_point(field_release:pswmgr.PasswordEntry.account_name)
  
  return account_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PasswordEntry::set_allocated_account_name(::std::string* account_name) {
  if (account_name != NULL) {
    
  } else {
    
  }
  account_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account_name);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.PasswordEntry.account_name)
}

// string username = 2;
inline void PasswordEntry::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PasswordEntry::username() const {
  // @@protoc_insertion_point(field_get:pswmgr.PasswordEntry.username)
  return username_.GetNoArena();
}
inline void PasswordEntry::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.PasswordEntry.username)
}
#if LANG_CXX11
inline void PasswordEntry::set_username(::std::string&& value) {
  
  username_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.PasswordEntry.username)
}
#endif
inline void PasswordEntry::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.PasswordEntry.username)
}
inline void PasswordEntry::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.PasswordEntry.username)
}
inline ::std::string* PasswordEntry::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.PasswordEntry.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PasswordEntry::release_username() {
  // @@protoc_insertion_point(field_release:pswmgr.PasswordEntry.username)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PasswordEntry::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.PasswordEntry.username)
}

// string password = 3;
inline void PasswordEntry::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PasswordEntry::password() const {
  // @@protoc_insertion_point(field_get:pswmgr.PasswordEntry.password)
  return password_.GetNoArena();
}
inline void PasswordEntry::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.PasswordEntry.password)
}
#if LANG_CXX11
inline void PasswordEntry::set_password(::std::string&& value) {
  
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.PasswordEntry.password)
}
#endif
inline void PasswordEntry::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.PasswordEntry.password)
}
inline void PasswordEntry::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.PasswordEntry.password)
}
inline ::std::string* PasswordEntry::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.PasswordEntry.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PasswordEntry::release_password() {
  // @@protoc_insertion_point(field_release:pswmgr.PasswordEntry.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PasswordEntry::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.PasswordEntry.password)
}

// string extra = 4;
inline void PasswordEntry::clear_extra() {
  extra_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PasswordEntry::extra() const {
  // @@protoc_insertion_point(field_get:pswmgr.PasswordEntry.extra)
  return extra_.GetNoArena();
}
inline void PasswordEntry::set_extra(const ::std::string& value) {
  
  extra_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pswmgr.PasswordEntry.extra)
}
#if LANG_CXX11
inline void PasswordEntry::set_extra(::std::string&& value) {
  
  extra_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pswmgr.PasswordEntry.extra)
}
#endif
inline void PasswordEntry::set_extra(const char* value) {
  
  extra_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pswmgr.PasswordEntry.extra)
}
inline void PasswordEntry::set_extra(const char* value, size_t size) {
  
  extra_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pswmgr.PasswordEntry.extra)
}
inline ::std::string* PasswordEntry::mutable_extra() {
  
  // @@protoc_insertion_point(field_mutable:pswmgr.PasswordEntry.extra)
  return extra_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PasswordEntry::release_extra() {
  // @@protoc_insertion_point(field_release:pswmgr.PasswordEntry.extra)
  
  return extra_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PasswordEntry::set_allocated_extra(::std::string* extra) {
  if (extra != NULL) {
    
  } else {
    
  }
  extra_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), extra);
  // @@protoc_insertion_point(field_set_allocated:pswmgr.PasswordEntry.extra)
}

// -------------------------------------------------------------------

// PasswordList

// repeated .pswmgr.PasswordEntry passwords = 1;
inline int PasswordList::passwords_size() const {
  return passwords_.size();
}
inline void PasswordList::clear_passwords() {
  passwords_.Clear();
}
inline const ::pswmgr::PasswordEntry& PasswordList::passwords(int index) const {
  // @@protoc_insertion_point(field_get:pswmgr.PasswordList.passwords)
  return passwords_.Get(index);
}
inline ::pswmgr::PasswordEntry* PasswordList::mutable_passwords(int index) {
  // @@protoc_insertion_point(field_mutable:pswmgr.PasswordList.passwords)
  return passwords_.Mutable(index);
}
inline ::pswmgr::PasswordEntry* PasswordList::add_passwords() {
  // @@protoc_insertion_point(field_add:pswmgr.PasswordList.passwords)
  return passwords_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pswmgr::PasswordEntry >*
PasswordList::mutable_passwords() {
  // @@protoc_insertion_point(field_mutable_list:pswmgr.PasswordList.passwords)
  return &passwords_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pswmgr::PasswordEntry >&
PasswordList::passwords() const {
  // @@protoc_insertion_point(field_list:pswmgr.PasswordList.passwords)
  return passwords_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace pswmgr

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pswmgr_2eproto__INCLUDED
